apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server-deployment
  labels:
    app: auth-server
spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-server

  template:
    metadata:
      labels:
        app: auth-server

    spec:
      containers:
      - name: auth-server
        image: mdmitrym/food_delivery_registration

        ports:
        - containerPort: 8000

        env:        
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: auth-sercret
                key: AUTH_POSTGRES_USER

          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-sercret
                key: AUTH_POSTGRES_PASSWORD

          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: auth-sercret
                key: AUTH_POSTGRES_DB

          - name: DB_SSL_MODE
            valueFrom:
              secretKeyRef:
                name: auth-sercret
                key: DB_SSL_MODE

          - name: AUTH_PORT
            valueFrom:
              secretKeyRef:
                name: auth-sercret
                key: AUTH_PORT
          
          - name: SIGNING_KEY
            valueFrom:
              secretKeyRef:
                name: auth-sercret
                key: SIGNING_KEY

          - name: AUTH_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: auth-config
                key: postgres-url

          - name: AUTH_DB_PORT
            valueFrom:
              secretKeyRef:
                name: auth-sercret
                key: AUTH_DB_PORT

          - name: JAEGER_URL
            valueFrom:
              configMapKeyRef:
                name: jaeger-config
                key: jaeger-url
        
          - name: JAEGER_PORT
            valueFrom:
              configMapKeyRef:
                name: jaeger-config
                key: jaeger-http-port
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server-service
spec:
  type: NodePort
  selector:
    app: auth-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100