apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server-deployment
  labels:
    app: api-server
spec:
  replicas: 1

  selector:
    matchLabels:
      app: api-server

  template:
    metadata:
      labels:
        app: api-server

    spec:
      containers:
      - name: api-server
        image: mdmitrym/food_delivery_api

        ports:
        - containerPort: 8080

        env:        
          - name: API_PORT
            valueFrom:
              secretKeyRef:
                    name: api-sercret
                    key: API_PORT

          - name: AUTH_HOST
            valueFrom:
              configMapKeyRef:
                    name: api-config
                    key: auth-url

          - name: AUTH_PORT
            valueFrom:
              secretKeyRef:
                    name: auth-sercret
                    key: AUTH_PORT
                    
          - name: RABBITMQ_URI
            valueFrom:
              secretKeyRef:
                name: rabbitmq-svcbind
                key: uri
          
          - name: JAEGER_URL
            valueFrom:
              configMapKeyRef:
                name: jaeger-config
                key: jaeger-url
        
          - name: JAEGER_PORT
            valueFrom:
              configMapKeyRef:
                name: jaeger-config
                key: jaeger-grpc-port
---
apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30200